/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_main_menu.java
 *
 * Created on May 20, 2013, 7:48:51 PM
 */

package com.java.bayes.apps.form;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;
/**
 *
 * @author Aries
 */
public class Frm_main_menu extends javax.swing.JFrame {

    /** Creates new form MainMenu */
    public Frm_main_menu() {
        initComponents();
        this.setLocationRelativeTo(getRootPane());
        setJam();
    }
    
    public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "",nol_detik = "";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";

                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                lbljam.setText(jam+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanelImageBackground1 = new wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground();
        lbljam = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_exit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mn_entry_data_training_1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mn_proses_1 = new javax.swing.JMenuItem();
        menuabout = new javax.swing.JMenu();
        mn_tentang = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jPanelImageBackground1.setGambar(new java.io.File("D:\\image\\wallpaper lucu 1 - Copy.jpg"));

        lbljam.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbljam.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImageBackground1Layout = new javax.swing.GroupLayout(jPanelImageBackground1);
        jPanelImageBackground1.setLayout(jPanelImageBackground1Layout);
        jPanelImageBackground1Layout.setHorizontalGroup(
            jPanelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageBackground1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbljam, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanelImageBackground1Layout.setVerticalGroup(
            jPanelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageBackground1Layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(lbljam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        mn_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mn_exit.setText("Exit");
        mn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mn_exit);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Data Training");

        mn_entry_data_training_1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mn_entry_data_training_1.setText("Entry Data Training 1");
        mn_entry_data_training_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_entry_data_training_1ActionPerformed(evt);
            }
        });
        jMenu4.add(mn_entry_data_training_1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Proses");

        mn_proses_1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        mn_proses_1.setText("Proses 1");
        mn_proses_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_proses_1ActionPerformed(evt);
            }
        });
        jMenu5.add(mn_proses_1);

        jMenuBar1.add(jMenu5);

        menuabout.setText("Bantuan");
        menuabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaboutActionPerformed(evt);
            }
        });

        mn_tentang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mn_tentang.setText("Tentang Aplikasi");
        mn_tentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_tentangActionPerformed(evt);
            }
        });
        menuabout.add(mn_tentang);

        jMenuBar1.add(menuabout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImageBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImageBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaboutActionPerformed
      Frm_about a = new Frm_about();
      a.setVisible(true);
    }//GEN-LAST:event_menuaboutActionPerformed

    private void jCheckBoxMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem10ActionPerformed
       
    }//GEN-LAST:event_jCheckBoxMenuItem10ActionPerformed

    private void mn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_exitActionPerformed
        // keluar aplikasi dan release resource //
        System.exit(0);
    }//GEN-LAST:event_mn_exitActionPerformed

    private void mn_entry_data_training_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_entry_data_training_1ActionPerformed
        Frm_data_training insert_data_training_1 = new Frm_data_training();
        insert_data_training_1.setVisible(true);
    }//GEN-LAST:event_mn_entry_data_training_1ActionPerformed

    private void mn_proses_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_proses_1ActionPerformed
        Frm_prediction_process proses_training_1 = new Frm_prediction_process();
        proses_training_1.setSize(1130, 480);
        proses_training_1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        proses_training_1.setLocationRelativeTo(null);
        proses_training_1.setVisible(true);              
    }//GEN-LAST:event_mn_proses_1ActionPerformed

    private void mn_tentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_tentangActionPerformed
        Frm_about tentang_aplikasi = new Frm_about();
        tentang_aplikasi.setVisible(true);
    }//GEN-LAST:event_mn_tentangActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground jPanelImageBackground1;
    private javax.swing.JLabel lbljam;
    private javax.swing.JMenu menuabout;
    private javax.swing.JMenuItem mn_entry_data_training_1;
    private javax.swing.JMenuItem mn_exit;
    private javax.swing.JMenuItem mn_proses_1;
    private javax.swing.JMenuItem mn_tentang;
    // End of variables declaration//GEN-END:variables

}
