/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_splash_screen.java
 *
 * Created on May 20, 2013, 11:26:20 PM
 */

package com.java.bayes.apps.form;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Aries
 */
public class Frm_splash_screen extends javax.swing.JFrame {
Timer timer;
   int time;
   
    public Frm_splash_screen() {
        initComponents();
        this.setLocationRelativeTo(getRootPane());
        timer=new Timer(0, new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    time++;
                    pbar.setValue(time);
                    if(pbar.getValue()==100){
                        pbar.setValue(0);
                        Frm_login mu=new Frm_login();
                        mu.setVisible(true);


                        dispose();
                        timer.stop();
                    }
                }
            });
            timer.start();



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImageBackground1 = new wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground();
        pbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelImageBackground1.setGambar(new java.io.File("D:\\image\\background prog 1.jpg"));

        javax.swing.GroupLayout jPanelImageBackground1Layout = new javax.swing.GroupLayout(jPanelImageBackground1);
        jPanelImageBackground1.setLayout(jPanelImageBackground1Layout);
        jPanelImageBackground1Layout.setHorizontalGroup(
            jPanelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageBackground1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanelImageBackground1Layout.setVerticalGroup(
            jPanelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageBackground1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImageBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImageBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws ParseException {
        try{
            UIManager.setLookAndFeel(new McWinLookAndFeel());
            new Frm_splash_screen().setVisible(true);
        }catch (UnsupportedLookAndFeelException ex){
            System.err.println("error"+ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground jPanelImageBackground1;
    private javax.swing.JProgressBar pbar;
    // End of variables declaration//GEN-END:variables

}
